# Docker Compose for STMS - Azure Tutorial Compliant
# For local development and testing

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.azure-tutorial
    ports:
      - "8080:8080"
    environment:
      - APP_KEY=base64:${APP_KEY:-dGVzdGluZ2tleWZvcmRldmVsb3BtZW50dXNlb25seQ==}
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=stms
      - DB_USERNAME=stms_user
      - DB_PASSWORD=stms_password
    depends_on:
      - mysql
    networks:
      - stms-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=stms
      - MYSQL_USER=stms_user
      - MYSQL_PASSWORD=stms_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - stms-network

volumes:
  mysql_data:

networks:
  stms-network:
    driver: bridge
